# Generated by Django 3.2 on 2022-05-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roombook', '0002_alter_booking_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
            ],
        ),
    ]
